In [9]:
'''А) Написать программу, которая на вход получает натуральное число N и
выводит N-е число ряда Фибоначчи на экран.
Пояснение: последовательность Фибоначчи — это ряд чисел, в котором
первые два элемента равны 1, а каждый следующий элемент равен сумме двух
предыдущих: 1, 1, 2, 3, 5, 8, 13, 21, ...'''

n = int(input())
a = 1
b = 1
if n >= 3:
    for i in range(n-2):
        a_new = a + b
        b = a
        a = a_new
print(a)

832040


In [19]:
'''В) Числа последовательно вводятся в цикле. Ввод завершается числом 0.
Определите индекс наибольшего элемента последовательности. Если
наибольших элементов несколько, выведите индекс первого из них. Нумерация
элементов начинается с нуля.
'''
max_n = None
temp = None
max_ind = None
counter = -1

while True:
    temp = float(input())
    if temp == 0:
        break
    counter += 1 
    if max_n == None or temp > max_n:
        max_n = temp
        max_ind = counter
print(f"Наибольший элемент: {max_n}\nИндекс первого: {max_ind} ")

Наибольший элемент: 32.0
Индекс первого: 1 


In [20]:
'''В) Числа последовательно вводятся в цикле. Ввод завершается числом 0.
Определите индекс наибольшего элемента последовательности. Если
наибольших элементов несколько, выведите индекс первого из них. Нумерация
элементов начинается с нуля.
'''
max_n = None
temp = None
max_ind = None
counter = -1

while temp != 0:
    temp = float(input())
    counter += 1 
    if max_n == None or temp > max_n:
        max_n = temp
        max_ind = counter
print(f"Наибольший элемент: {max_n}\nИндекс первого: {max_ind} ")

Наибольший элемент: 4.0
Индекс первого: 0 


In [28]:
'''Напишите программу, которая принимает на вход список букв в одной
строке (через генератор). Сформируйте список из гласных букв'''

n = str(input())
vowels = set('eyuioaEYUIOAуеыаоэяиюёУЕЫАОЭЯИЮЁ')

list_let = [let for let in n if let in vowels and let.isalpha()]
print(list_let)

['y', 'y', 'y']


In [35]:
'''А) Напишите программу, которая анализирует текст на основе словаря,
содержащий название города и количество жителей и сообщает к какой
категории этот город относится.
По признаку численности населения города классифицируются следующим
образом:
 свыше 1 млн чел – крупнейшие;
 от 250 тыс чел – до 1 млн чел – крупные;
 от 100 до 250 тыс чел – большие;
 от 50 до 100 тыс чел – средние;
 до 50 тыс чел – малые.'''

city_dict = {
    "москва": 13149803,
    "санкт-Петербург": 5597763,
    "новосибирск": 1633851,
    "екатеринбург": 1536183,
    "казань": 1318604,
    "нижний Новгород": 1204985,
    "челябинск": 1177058,
    "уфа": 1163304,
    "самара": 1158952,
    "ростов-на-Дону": 1140487,
    "краснодар": 1138654,
    "пермь": 1026908,
    "волгоград": 1018898,
    "саратов": 887365,
    "тюмень": 861098,
    "плёс": 1896,
    "мышкин": 2230,
    "касимов": 23500,
    "тотьма": 8647,
    "сольвычегодск": 1952
}

corpus = input().split()
for word in corpus:
    if word.lower() in city_dict:
        if city_dict[word] >= 1000000:
            result = 'крупнейший'
        elif city_dict[word] >= 250000:
            result = 'крупный'
        elif city_dict[word] >= 100000:
            result = 'большой'
        elif city_dict[word] >= 50000:
            result = 'средний'
        else:
            result = 'малый'
        print(word, result)

Казань крупнейший
Тотьма малый


In [64]:
'''до 50 тыс чел – малые.
В) Выполните на основе набора данных data.json задание: Какой клиент
(client_id) совершил наибольшее количество действий с (category) = datepicker'''

import json
from collections import Counter
with open('data.json', mode = 'r', encoding = 'cp1251') as f:
    data = json.load(f)
    
data = data.get('events_data', []) 
target_category = 'datepicker'

ids = [item['id'] for item in data if item.get('category') == target_category]
max_count = Counter(ids).most_common(1)
print(f"Клиент с максимальным количеством действий с {target_category}: {max_count[0][0]}")
print(f"Kоличество действий с {target_category}: {max_count[0][1]}")

Клиент с максимальным количеством действий с datepicker: 47962120
Kоличество действий с datepicker: 1


In [75]:
'''8. Сформировать целочисленную матрицу А[n,m] с помощью генератора
случайных чисел (random). Отсортировать матрицу по убыванию элементов
последнего столбца.
Вычислить среднее значение элементов последнего столбца. Ответ
округлите до сотых. Вычисление среднего значения выполнить двумя
способами: через стандартную функцию и через программирование формулы'''

import numpy as np

rng = np.random.default_rng(42)
n,m = list(map(int, input().split()))
matrix = rng.random((n,m))
print(f"Случайная матрица:\n{matrix}")
col_idx = m-1
ids = matrix[:,col_idx].argsort()
print(f"Сортированная матрица:\n{matrix[matrix[:,col_idx].argsort()]}")
mean = matrix[:,col_idx].mean()
print(matrix[:,col_idx])

Случайная матрица:
[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]
Сортированная матрица:
[[0.7611397  0.78606431 0.12811363]
 [0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
[0.85859792 0.97562235 0.12811363]


In [61]:
?np.sort